<?xml version="1.0" encoding="UTF-8"?>
<project name="SkillSwapCampus" default="default" basedir="." xmlns:webproject1="http://www.netbeans.org/ns/web-project/1" xmlns:webproject2="http://www.netbeans.org/ns/web-project/2" xmlns:webproject3="http://www.netbeans.org/ns/web-project/3">
    <description>Builds, tests, and runs the project SkillSwapCampus.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
